$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: sklearn-deployment
endpoint_name: realtime-diabetes-dev
model:
  name: sk-diabetes-model
  version: 11
  path: sk-diabetes-model/model
  model_format: mlflow
instance_type: Standard_E2s_v3
instance_count: 3